#!/usr/bin/env python3
"""QGIS layer styles, generated from the annotation schema of record.

A reviewer opening a delivered GeoPackage should meet the same form the
annotator meets in CVAT: checkboxes for the boolean attributes, dropdowns
offering exactly the allowed values, and nothing editable that is bookkeeping.
Without that, the fields arrive as free text, reviewers type whatever reads
sensibly, and ``ingest_review`` rejects the result after the work is done.

**The style is generated from ``annotation/cvat/labels.json``, never written by
hand.** That file is the schema of record, and a style listing its own copy of
the vocabularies is the same drift that put five attributes CVAT does not emit
into ``PROTOCOL_EN.md``. Regenerate when the schema changes and the two cannot
disagree.

**The style is stored inside the GeoPackage, not beside it.** QGIS picks up a
``<name>.qml`` sitting next to a single-layer file, but a GeoPackage holds two
layers in one container and the convention does not reach them; a delivery of
57 sheets would mean loading 114 styles by hand. QGIS instead reads a
``layer_styles`` table from inside the container and applies any row flagged
``useAsDefault``. The table is a QGIS convention rather than part of the
GeoPackage standard, so it is registered in ``gpkg_contents`` as an attributes
table and the file stays valid for tools that have never heard of it.

Usage:
    python -m archeo_topia.formats.styles \\
        --schema annotation/cvat/labels.json \\
        --bundle "$LAKE/cleaned/gis/v0_7_review_bundle"
"""

from __future__ import annotations

import argparse
import logging
import sqlite3
from pathlib import Path

from archeo_topia.formats.labels import LabelSchema

logger = logging.getLogger(__name__)

#: The schema of record.
DEFAULT_SCHEMA = Path("annotation/cvat/labels.json")

#: The label whose attributes the point form exposes. Reviewers judge mounds;
#: the other two classes exist in the schema but are not proposed by the
#: detector and so never reach a delivered layer.
REVIEW_LABEL = "mound"

#: Fields a reviewer must not edit, shown greyed out in the form. ``mound_id``
#: is how a verdict is matched back to the proposal it answers, ``split``
#: records whether the sheet may be trained on, and the coordinates are the
#: model's own output rather than anything a review establishes.
LOCKED_FIELDS = (
    "mound_id",
    "sheet_id",
    "source_image",
    "clip_x",
    "clip_y",
    "sheet_x",
    "sheet_y",
    "split",
    "detector_confidence",
)

#: Colours for the ``review_status`` categories, so progress through a sheet is
#: visible on the map without opening the attribute table. Grey reads as "not
#: looked at yet", which is the state every feature ships in.
STATUS_COLOURS = {
    "unreviewed": "150,150,150,255",
    "confirmed": "35,140,60,255",
    "rejected": "200,40,40,255",
    "corrected": "230,150,20,255",
    "added": "40,90,200,255",
}

#: The symbol layer is the printed cartographic mark, not the mound's ground
#: extent, so it is drawn as an unfilled outline. A filled polygon invites
#: exactly the misreading ``TARGET_PIPELINE.md`` warns about.
SYMBOL_STYLE = """<!DOCTYPE qgis PUBLIC 'http://mapserver.org/~lars/qgis.dtd' 'SYSTEM'>
<!-- Generated by archeo_topia.formats.styles. Do not hand-edit.
     This is the printed cartographic symbol, NOT the mound's ground extent. -->
<qgis version="3.28.0" styleCategories="Symbology|Fields|Forms">
  <renderer-v2 type="singleSymbol" forceraster="0" symbollevels="0">
    <symbols>
      <symbol type="fill" name="0"><layer class="SimpleFill">
        <Option type="Map">
          <Option name="color" type="QString" value="0,0,0,0"/>
          <Option name="outline_color" type="QString" value="80,80,220,255"/>
          <Option name="outline_width" type="QString" value="0.3"/>
          <Option name="style" type="QString" value="no"/>
        </Option>
      </layer></symbol>
    </symbols>
  </renderer-v2>
  <editable>
    <field name="mound_id" editable="0"/>
    <field name="sheet_id" editable="0"/>
    <field name="symbol_area_px" editable="0"/>
    <field name="detector_to_mask_centroid_distance_px" editable="0"/>
  </editable>
</qgis>
"""

_LAYER_STYLES_DDL = """
CREATE TABLE IF NOT EXISTS layer_styles (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  f_table_catalog TEXT(256), f_table_schema TEXT(256), f_table_name TEXT(256),
  f_geometry_column TEXT(256), styleName TEXT(30), styleQML TEXT, styleSLD TEXT,
  useAsDefault BOOLEAN, description TEXT, owner TEXT(30), ui TEXT(30),
  update_time DATETIME NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
"""


def _checkbox(name: str) -> str:
    """Return the field configuration for a boolean attribute.

    GeoPackage stores these as ``Integer(Boolean)``, so the widget's checked
    and unchecked states are ``1`` and ``0`` rather than CVAT's ``"true"`` and
    ``"false"``.
    """
    return f"""    <field name="{name}">
      <editWidgetSetup type="CheckBox">
        <config><Option type="Map">
          <Option name="CheckedState" type="QString" value="1"/>
          <Option name="UncheckedState" type="QString" value="0"/>
        </Option></config>
      </editWidgetSetup>
    </field>"""


def _value_map(name: str, values: list[str]) -> str:
    """Return the field configuration for a select attribute."""
    entries = "\n".join(
        f'            <Option type="Map">'
        f'<Option name="{value}" type="QString" value="{value}"/></Option>'
        for value in values
    )
    return f"""    <field name="{name}">
      <editWidgetSetup type="ValueMap">
        <config><Option type="Map">
          <Option name="map" type="List">
{entries}
          </Option>
        </Option></config>
      </editWidgetSetup>
    </field>"""


def _marker(index: int, colour: str) -> str:
    """Return one categorized-renderer marker symbol."""
    return (
        f'      <symbol type="marker" name="{index}"><layer class="SimpleMarker">'
        f'<Option type="Map">'
        f'<Option name="color" type="QString" value="{colour}"/>'
        f'<Option name="name" type="QString" value="circle"/>'
        f'<Option name="outline_color" type="QString" value="35,35,35,255"/>'
        f'<Option name="outline_width" type="QString" value="0.2"/>'
        f'<Option name="size" type="QString" value="3"/>'
        f"</Option></layer></symbol>"
    )


def build_point_style(schema: LabelSchema) -> str:
    """Build the ``mound_points`` style from the schema.

    Args:
        schema: The label schema of record.

    Returns:
        A QGIS ``.qml`` document.

    Raises:
        KeyError: If the schema carries no ``mound`` label.
    """
    fields = []
    for attribute in schema.attributes(REVIEW_LABEL):
        name = attribute["name"]
        if attribute["input_type"] == "checkbox":
            fields.append(_checkbox(name))
        elif attribute["input_type"] == "select":
            fields.append(_value_map(name, attribute["values"]))

    categories = [
        f'      <category render="true" value="{status}" symbol="{i}" label="{status}"/>'
        for i, status in enumerate(STATUS_COLOURS)
    ]
    symbols = [_marker(i, colour) for i, colour in enumerate(STATUS_COLOURS.values())]
    locked = [f'    <field name="{name}" editable="0"/>' for name in LOCKED_FIELDS]

    newline = "\n"
    version = schema.document.get("schema_version", "")
    return f"""<!DOCTYPE qgis PUBLIC 'http://mapserver.org/~lars/qgis.dtd' 'SYSTEM'>
<!-- Generated by archeo_topia.formats.styles from schema {version}.
     Do not hand-edit: regenerate when the CVAT label schema changes. -->
<qgis version="3.28.0" styleCategories="Symbology|Fields|Forms">
  <renderer-v2 type="categorizedSymbol" attr="review_status" forceraster="0" symbollevels="0">
    <categories>
{newline.join(categories)}
    </categories>
    <symbols>
{newline.join(symbols)}
    </symbols>
  </renderer-v2>
  <fieldConfiguration>
{newline.join(fields)}
  </fieldConfiguration>
  <editable>
{newline.join(locked)}
  </editable>
</qgis>
"""


def embed(gpkg: Path, styles: dict[str, str], schema_version: str = "") -> None:
    """Write styles into one GeoPackage's ``layer_styles`` table.

    Existing rows are replaced rather than appended to, so re-running is
    idempotent and a stale vocabulary cannot survive a regeneration.

    Args:
        gpkg: The GeoPackage to modify in place.
        styles: Layer name to QML document.
        schema_version: Recorded in the row description, for provenance.
    """
    connection = sqlite3.connect(gpkg)
    try:
        connection.executescript(_LAYER_STYLES_DDL)
        connection.execute("DELETE FROM layer_styles")
        for layer, qml in styles.items():
            connection.execute(
                "INSERT INTO layer_styles (f_table_catalog, f_table_schema, "
                "f_table_name, f_geometry_column, styleName, styleQML, styleSLD, "
                "useAsDefault, description, owner, ui) "
                "VALUES ('', '', ?, 'geom', ?, ?, '', 1, ?, 'ai_archaeo_topia', NULL)",
                (
                    layer,
                    f"{layer}_cvat",
                    qml,
                    f"Attribute form and colours matching CVAT schema {schema_version}",
                ),
            )
        connection.execute(
            "INSERT OR IGNORE INTO gpkg_contents (table_name, data_type, "
            "identifier, description) VALUES ('layer_styles', 'attributes', "
            "'layer_styles', 'QGIS layer styles')"
        )
        connection.commit()
    finally:
        connection.close()


def apply_to_bundle(bundle: Path, schema: LabelSchema) -> int:
    """Embed styles into every GeoPackage under a delivery directory.

    Args:
        bundle: A delivery root; searched recursively.
        schema: The label schema of record.

    Returns:
        The number of GeoPackages modified.
    """
    styles = {
        "mound_points": build_point_style(schema),
        "mound_symbols": SYMBOL_STYLE,
    }
    count = 0
    for gpkg in sorted(bundle.rglob("*.gpkg")):
        embed(gpkg, styles, schema.document.get("schema_version", ""))
        count += 1
        logger.debug("embedded styles into %s", gpkg)
    logger.info("embedded styles into %d GeoPackage(s) under %s", count, bundle)
    return count


def main() -> None:
    """Command-line entry point."""
    parser = argparse.ArgumentParser(description="QGIS styles from the label schema")
    parser.add_argument("--schema", default=str(DEFAULT_SCHEMA))
    parser.add_argument("--bundle", help="Delivery root; every .gpkg under it is styled")
    parser.add_argument("--write-qml", help="Also write the .qml files to this directory")
    parser.add_argument("--log-level", default="INFO")
    args = parser.parse_args()

    logging.basicConfig(level=args.log_level, format="%(asctime)s %(levelname)s %(message)s")
    schema = LabelSchema.load(args.schema)

    if args.write_qml:
        directory = Path(args.write_qml)
        directory.mkdir(parents=True, exist_ok=True)
        (directory / "mound_points.qml").write_text(build_point_style(schema), encoding="utf-8")
        (directory / "mound_symbols.qml").write_text(SYMBOL_STYLE, encoding="utf-8")
        logger.info("wrote %s/mound_points.qml and mound_symbols.qml", directory)

    if args.bundle:
        apply_to_bundle(Path(args.bundle), schema)

    if not args.bundle and not args.write_qml:
        parser.error("nothing to do: pass --bundle, --write-qml, or both")


if __name__ == "__main__":
    main()
